#page title
page_title                                :   Esse - Effortless text transformation                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1438921989                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Swiss army knife of text transformation for iOS and macOS
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ameba                                
your_link                                 : https://ameba.co                    
your_city                                 : Washington DC                                
email_address                             : info@ameba.co
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : amebalabs
github_username                           : amebalabs
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Quick Transform 
    description                           : Dozens of text transformations at your fingertips, type text and copy or share transformation result in one tap.
    fontawesome_icon_name                 : magic
    
  - title                                 : Scratchpad
    description                           : Combine several text transformation functions in one to create a more powerful transformation.
    fontawesome_icon_name                 : mobile

  - title                                 : Siri Shortcuts
    description                           : All Esse functions are available through Siri Shortcuts, include it in your productivity workflow.
    fontawesome_icon_name                 : microphone

  - title                                 : External Scripts
    description                           : Add new custom functions in JavaScript.
    fontawesome_icon_name                 : code

  - title                                 : Today Widget
    description                           : One tap clipboard text transformation using the Today Widget.
    fontawesome_icon_name                 : th

  - title                                 : Share Sheet
    description                           : Use Share Sheet to quickly transform text and copy it to the clipboard.
    fontawesome_icon_name                 : share-square

  - title                                 : Menu Bar App
    description                           : One-click text transformations easily available in macOS menu bar.
    fontawesome_icon_name                 : ellipsis-h
  
  - title                                 : Command Line Tool
    description                           : Access Esse functions in terminal.
    fontawesome_icon_name                 : terminal

  - title                                 : Dark Mode
    description                           : Support for dark mode makes for those late night text transformation.
    fontawesome_icon_name                 : moon



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#e48633"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#e48633"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
